import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { Playbook } from '../models/Playbook';
import { EscalationRule } from '../models/EscalationRule';

const router: Router = Router();

const DEFAULT_PLAYBOOKS = [
  {
    name: 'Critical Phishing Takedown', description: 'Auto-takedown for critical phishing sites with SLA escalation',
    trigger: 'THREAT_DETECTED', severity: ['CRITICAL', 'HIGH'], status: 'ACTIVE',
    steps: [
      { stepId: '1', name: 'Execute Takedown', type: 'TAKEDOWN', config: { platform: 'KOMINFO', autoGenerateDraft: true }, timeout: 300, order: 1 },
      { stepId: '2', name: 'Create Incident Ticket', type: 'TICKET', config: { priority: 'P1', assignee: 'SOC_ANALYST' }, timeout: 60, order: 2 },
      { stepId: '3', name: 'Notify SOC Team', type: 'NOTIFY', config: { channel: 'slack', message: 'Critical takedown initiated' }, timeout: 30, order: 3 },
      { stepId: '4', name: 'Approval: Manager Review', type: 'APPROVAL', config: { requiredRole: 'SOC_MANAGER' }, timeout: 1440, order: 4 },
    ],
  },
  {
    name: 'Malware Block & Report', description: 'Automated IP blocking and abuse reporting for malware',
    trigger: 'VULNERABILITY_FOUND', severity: ['CRITICAL'], status: 'ACTIVE',
    steps: [
      { stepId: '1', name: 'Block IP at Firewall', type: 'BLOCK', config: { provider: 'CLOUDFLARE', duration: '24h' }, timeout: 120, order: 1 },
      { stepId: '2', name: 'Generate Abuse Report', type: 'EMAIL', config: { template: 'abuse', includeEvidence: true }, timeout: 60, order: 2 },
      { stepId: '3', name: 'Create Jira Ticket', type: 'TICKET', config: { project: 'SOC', priority: 'P2' }, timeout: 60, order: 3 },
    ],
  },
  {
    name: 'Escalation: Critical Incident', description: 'Multi-tier escalation for critical incidents',
    trigger: 'INCIDENT_CREATED', severity: ['CRITICAL'], status: 'ACTIVE',
    steps: [
      { stepId: '1', name: 'Level-1: SOC Analyst', type: 'NOTIFY', config: { role: 'SOC_ANALYST', method: 'PUSH' }, timeout: 15, order: 1 },
      { stepId: '2', name: 'Level-2: SOC Manager', type: 'ESCALATE', config: { targetRole: 'SOC_MANAGER' }, timeout: 30, order: 2 },
      { stepId: '3', name: 'Level-3: CISO', type: 'ESCALATE', config: { targetRole: 'SUPER_ADMIN', method: 'SMS' }, timeout: 60, order: 3 },
    ],
  },
];

const DEFAULT_ESCALATIONS = [
  { name: 'Critical Unresolved > 1 Hour', condition: [{ field: 'severity', operator: 'EQ', value: 'CRITICAL' }, { field: 'status', operator: 'EQ', value: 'IN_REVIEW' }], timeoutMinutes: 60, escalateTo: ['SOC_MANAGER'], notifyChannels: ['slack', 'email'] },
  { name: 'High Takedown > 24 Hours', condition: [{ field: 'severity', operator: 'EQ', value: 'HIGH' }, { field: 'status', operator: 'EQ', value: 'SUBMITTED' }], timeoutMinutes: 1440, escalateTo: ['SOC_MANAGER', 'TENANT_ADMIN'], notifyChannels: ['email'] },
  { name: 'SLA Breach: Critical', condition: [{ field: 'slaBreached', operator: 'EQ', value: 'true' }], timeoutMinutes: 0, escalateTo: ['SUPER_ADMIN'], notifyChannels: ['sms', 'email'] },
];

// ═══ GET /automation/dashboard — Summary ═══
router.get('/dashboard', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).user?.tenantId || 'default';
    const playbooks = await Playbook.countDocuments({ tenantId });
    const activePl = await Playbook.countDocuments({ tenantId, status: 'ACTIVE' });
    const escalations = await EscalationRule.countDocuments({ tenantId });
    const activeEs = await EscalationRule.countDocuments({ tenantId, status: 'ACTIVE' });
    res.json({ playbooks, activePlaybooks: activePl, escalations, activeEscalations: activeEs });
  } catch { res.status(500).json({ error: 'INTERNAL' }); }
});

// ═══ GET /automation/playbooks — List playbooks ═══
router.get('/playbooks', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).user?.tenantId || 'default';
    let data = await Playbook.find({ tenantId }).sort({ createdAt: -1 }).lean();
    if (data.length === 0) {
      await Playbook.insertMany(DEFAULT_PLAYBOOKS.map(p => ({ ...p, tenantId })));
      data = await Playbook.find({ tenantId }).sort({ createdAt: -1 }).lean();
    }
    res.json({ data });
  } catch { res.status(500).json({ error: 'INTERNAL' }); }
});

// ═══ GET /automation/escalations — List escalation rules ═══
router.get('/escalations', async (req: Request, res: Response) => {
  try {
    const tenantId = (req as any).user?.tenantId || 'default';
    let data = await EscalationRule.find({ tenantId }).sort({ createdAt: -1 }).lean();
    if (data.length === 0) {
      await EscalationRule.insertMany(DEFAULT_ESCALATIONS.map(e => ({ ...e, tenantId })));
      data = await EscalationRule.find({ tenantId }).sort({ createdAt: -1 }).lean();
    }
    res.json({ data });
  } catch { res.status(500).json({ error: 'INTERNAL' }); }
});

export default router;
